[package]
name = "lishp"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "^0.12.0"
dot = "^0.1"

[build-dependencies]
lalrpop = "0.12.0"
